- hosts: all
  gather_facts: no
  tasks:
    - name: Test ce_command with paramiko_ssh
      community.network.ce_command:
        commands: display clock
      register: result
    - debug: var=result.stdout_lines
